{
 "title": "Mail traffic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Postfix Conections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_connection",
     "query": "SELECT count(\"method\") FROM \"postfix_connection\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dovecot Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "dovecot_login_ok",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Accepted Mails",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_queued",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Relayed Mails",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_relayed",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dovecot Auth Fail hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "dovecot_auth_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Auth Fails hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_nq_access_denied_client",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unknown recipient hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_nq_user_unknown",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mailbox full hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_nq_mailbox_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Starts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_start",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Reloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_reload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Internal Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_nq_internal_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Config Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "postfix_nq_server_config_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dovecot Login Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IMAP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_login_ok",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "via", "operator": "=", "value": "imap" }
     ]
    },
    {
     "alias": "POP3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_login_ok",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "via", "operator": "=", "value": "pop" }
     ]
    }
   ]
  },
  {
   "title": "Postfix Mail traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Successful connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_connection",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Auth senders",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_sasl_auth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Queued mails",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_queued",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Relayed mails",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_relayed",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dovecot Problems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Login Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_auth_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Auth service not responding",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_auth_process_not_responding",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Droped before login",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_drop_no_auth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "LDAP unreachable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_ldap_unreachable",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Quota errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_quota_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Client broke auth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dovecot_client_broke_auth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix Problems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Reloads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_reload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Starts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_start",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Unknown user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_nq_user_unknown",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Timeouts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_timeout",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Invalid_user_settings",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_nq_invalid_user_settings",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Client_denied",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_nq_access_denied_client",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Mailbox full",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_nq_mailbox_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Server Config error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_nq_server_config_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Internal Error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postfix_nq_internal_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Users with mailbox full",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_to",
     "groupBy": [
      { "params": [ "to" ], "type": "tag" }
     ],
     "measurement": "postfix_nq_mailbox_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most used ciphers by clients (postfix)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_cipher",
     "groupBy": [
      { "params": [ "cipher" ], "type": "tag" }
     ],
     "measurement": "postfix_tls_connect",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dovecot Login errors by User",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "dovecot_auth_failed",
     "query": "SELECT count(\"user\") FROM \"dovecot_auth_failed\" WHERE $timeFilter GROUP BY \"rip\" LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postfix sender Count by User",
   "type": "bargauge",
   "gridPos": { "h": 44, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_sasl_username",
     "groupBy": [
      { "params": [ "sasl_username" ], "type": "tag" }
     ],
     "limit": 10,
     "measurement": "postfix_sasl_auth",
     "query": "SELECT count(\"value\") as hits FROM \"postfix_sasl_auth\" WHERE $timeFilter GROUP BY \"sasl_username\" ORDER BY hits DESC LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dovecot recipients",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_to",
     "groupBy": [
      { "params": [ "to" ], "type": "tag" }
     ],
     "measurement": "dovecot_delivered",
     "query": "SELECT count(\"user\") FROM \"dovecot_auth_failed\" WHERE $timeFilter GROUP BY \"rip\" LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}